### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by minhdtb** [github/lightcrawler#12]
I have created a test project, but it occured an error when trying to run

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at Object.exports.spawn (child_process.js:369:9)
....

Any ideas?

**Comment by Zougi** [comment]
I got a similar error. Tested on node v9.8.0 and node v7.2.0 with readme's  _lightcrawler-config.json_
```
$ npm i -g lightcrawler
$ lightcrawler -u https://github.com -c lightcrawler-config.json
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:385:9)
    at runLighthouse (C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\index.js:75:35)
    at queue (C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\index.js:40:5)
    at C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\node_modules\async\queue.js:10:5
    at Object.process (C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\node_modules\async\internal\queue.js:175:17)
    at C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\node_modules\async\internal\queue.js:82:19
    at Immediate.<anonymous> (C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\node_modules\async\internal\setImmediate.js:27:16)
    at runCallback (timers.js:649:20)internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:385:9)
    at runLighthouse (C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\index.js:75:35)
    at queue (C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\index.js:40:5)
    at C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\node_modules\async\queue.js:10:5
    at Object.process (C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\node_modules\async\internal\queue.js:175:17)
    at C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\node_modules\async\internal\queue.js:82:19
    at Immediate.<anonymous> (C:\Users\zougi\AppData\Roaming\nvm\v7.2.0\node_modules\lightcrawler\node_modules\async\internal\setImmediate.js:27:16)
    at runCallback (timers.js:649:20)
```

**Comment by 0xd5** [comment]
Anyone looking into this? Any resolution?

**Comment by 0xd5** [comment]
Happens because of running on Windows, replaced lines 74/75 of index.js in d5dd416 with

```javascript
  const lighthousePath = require.resolve('lighthouse/lighthouse-cli/index.js');

  const lighthouse = ChildProcess.spawn('node', [lighthousePath, ...args]);
```

Going to test more extensively before making PR
